"""The catalogue we want: the famous dishes of the Philippines, by category.

Each entry is (id, display name, alt names, match terms). `match` terms must ALL
appear in a candidate URL slug for it to be considered; the least-cluttered
matching slug wins (see pick_url in build-recipes.py).
"""

# English UI name per category, in browse order (the D1 chips). The Filipino key
# stays the data value in recipes.json.
CATEGORIES = {
    "ulam na karne": "Meat",
    "ulam na isda": "Seafood",
    "sabaw": "Soups",
    "gulay": "Vegetables",
    "pancit at kanin": "Noodles & rice",
    "pulutan at meryenda": "Snacks",
    "panghimagas": "Desserts",
}

# (id, name, alt[], match_terms[])
DISHES = {
    "ulam na karne": [
        ("adobong-manok", "Adobong Manok", ["chicken adobo"], ["chicken", "adobo"]),
        ("adobong-baboy", "Adobong Baboy", ["pork adobo"], ["pork", "adobo"]),
        ("adobo-sa-gata", "Adobo sa Gata", ["coconut adobo"], ["adobo", "gata"]),
        ("adobong-kambing", "Adobong Kambing", ["goat adobo"], ["adobong", "kambing"]),
        ("kaldereta-baka", "Kalderetang Baka", ["beef caldereta"], ["beef", "kaldereta"]),
        ("kaldereta-kambing", "Kalderetang Kambing", ["goat caldereta"], ["kalderetang", "kambing"]),
        ("kaldereta-manok", "Kalderetang Manok", ["chicken caldereta"], ["chicken", "caldereta"]),
        ("mechado", "Mechado", ["beef mechado"], ["mechado"]),
        ("afritada", "Afritadang Manok", ["chicken afritada"], ["chicken", "afritada"]),
        ("afritada-baboy", "Afritadang Baboy", ["pork afritada"], ["pork", "afritada"]),
        ("menudo", "Menudo", ["pork menudo"], ["pork", "menudo"]),
        ("pochero", "Pochero", ["puchero"], ["pochero"]),
        ("bistek", "Bistek Tagalog", ["filipino beef steak"], ["bistek", "tagalog"]),
        ("dinuguan", "Dinuguan", ["pork blood stew"], ["dinuguan"]),
        ("sisig", "Sisig", ["pork sisig"], ["pork", "sisig"]),
        ("lechon-kawali", "Lechon Kawali", ["crispy fried pork belly"], ["lechon", "kawali"]),
        ("crispy-pata", "Crispy Pata", [], ["crispy", "pata"]),
        ("humba", "Humba", ["braised pork humba"], ["humba"]),
        ("hamonado", "Hamonado", ["pork hamonado"], ["hamonado"]),
        ("tapa", "Beef Tapa", ["tapsilog"], ["beef", "tapa"]),
        ("tocino", "Tocino", ["pork tocino"], ["tocino"]),
        ("longganisa", "Longganisa", ["filipino sausage"], ["longganisa"]),
        ("embutido", "Embutido", ["filipino meatloaf"], ["embutido"]),
        ("morcon", "Morcon", ["beef morcon"], ["morcon"]),
        ("bopis", "Bopis", [], ["bopis"]),
        ("igado", "Igado", [], ["igado"]),
        ("asado", "Asadong Baboy", ["pork asado"], ["pork", "asado"]),
        ("bicol-express", "Bicol Express", [], ["bicol", "express"]),
        ("binagoongan", "Binagoongang Baboy", ["pork binagoongan"], ["binagoongan"]),
        ("lechon-belly", "Lechon Belly", ["roast pork belly"], ["lechon", "belly"]),
        ("chicken-inasal", "Chicken Inasal", ["inasal na manok"], ["chicken", "inasal"]),
        ("fried-chicken", "Filipino Fried Chicken", [], ["filipino", "fried", "chicken"]),
        ("beef-steak-tagalog", "Beef Salpicao", ["salpicao"], ["salpicao"]),
        ("pata-tim", "Pata Tim", ["braised pork hock"], ["pata", "tim"]),
        ("kare-kare", "Kare-Kare", ["oxtail peanut stew"], ["kare-kare"]),
        ("callos", "Callos", ["tripe stew"], ["callos"]),
        ("caldereta-pork", "Kalderetang Baboy", ["pork caldereta"], ["pork", "kaldereta"]),
        ("adobong-pusit", "Adobong Pusit", ["squid adobo"], ["adobong", "pusit"]),
        ("chicken-curry", "Filipino Chicken Curry", ["curry manok"], ["chicken", "curry"]),
        ("giniling", "Giniling na Baboy", ["pork giniling", "picadillo"], ["giniling"]),
        ("tortang-giniling", "Tortang Giniling", ["ground pork omelette"], ["tortang", "giniling"]),
        ("adobo-flakes", "Adobo Flakes", [], ["adobo", "flakes"]),
        ("beef-tapa-adobo", "Adobong Baka", ["beef adobo"], ["beef", "adobo"]),
        ("lengua", "Lengua Estofado", ["ox tongue"], ["lengua"]),
        ("chicken-pastel", "Chicken Pastel", [], ["chicken", "pastel"]),
        ("beef-pares", "Beef Pares", [], ["beef", "pares"]),
        ("tapa-chicken", "Chicken Tapa", [], ["chicken", "tapa"]),
        ("pininyahang-manok", "Pininyahang Manok", ["pineapple chicken"], ["pininyahang", "manok"]),
        ("chicken-relleno", "Rellenong Manok", ["stuffed chicken"], ["rellenong", "manok"]),
        ("sinuglaw", "Sinuglaw", ["grilled pork and kinilaw"], ["sinuglaw"]),
    ],
    "ulam na isda": [
        ("sinigang-hipon", "Sinigang na Hipon", ["shrimp sinigang"], ["sinigang", "hipon"]),
        ("sinigang-bangus", "Sinigang na Bangus", ["milkfish sinigang"], ["sinigang", "bangus"]),
        ("sinigang-sugpo", "Sinigang na Sugpo", ["prawn sinigang"], ["sinigang", "sugpo"]),
        ("rellenong-alimasag", "Rellenong Alimasag", ["stuffed crab"], ["rellenong", "alimasag"]),
        ("daing-na-bangus", "Daing na Bangus", ["marinated milkfish"], ["daing", "bangus"]),
        ("paksiw-na-isda", "Paksiw na Isda", ["fish in vinegar"], ["paksiw", "isda"]),
        ("paksiw-na-bangus", "Paksiw na Bangus", [], ["paksiw", "bangus"]),
        ("escabeche", "Escabecheng Isda", ["sweet and sour fish"], ["escabeche"]),
        ("kinilaw", "Kinilaw na Tanigue", ["filipino ceviche"], ["kinilaw"]),
        ("ginataang-tilapia", "Ginataang Tilapia", [], ["ginataang", "tilapia"]),
        ("inihaw-na-bangus", "Inihaw na Bangus", ["grilled milkfish"], ["inihaw", "bangus"]),
        ("pritong-tilapia", "Pritong Tilapia", ["fried tilapia"], ["fried", "tilapia"]),
        ("sweet-sour-fish", "Sweet and Sour Fish", [], ["sweet", "sour", "fish"]),
        ("ginataang-hipon", "Ginataang Hipon", ["shrimp in coconut milk"], ["ginataang", "hipon"]),
        ("halabos-na-hipon", "Halabos na Hipon", ["steamed shrimp"], ["halabos"]),
        ("sinigang-salmon", "Sinigang na Salmon", [], ["sinigang", "salmon"]),
        ("pesang-isda", "Pesang Isda", ["fish in ginger broth"], ["pesang", "isda"]),
        ("tinolang-isda", "Tinolang Isda", ["fish tinola"], ["tinolang", "isda"]),
        ("adobong-hipon", "Adobong Hipon", ["shrimp adobo"], ["adobong", "hipon"]),
        ("bangus-belly", "Bangus Belly", [], ["bangus", "belly"]),
        ("pinangat-na-isda", "Pinangat na Isda", [], ["pinangat", "isda"]),
        ("sarciadong-isda", "Sarciadong Isda", [], ["sarciado"]),
        ("ginataang-alimasag", "Ginataang Alimasag", ["crab in coconut milk"], ["ginataang", "alimasag"]),
        ("chili-crab", "Chili Crab", ["alimasag"], ["chili", "crab"]),
        ("calamares", "Calamares", ["fried squid rings"], ["calamares"]),
        ("tuna-panga", "Inihaw na Panga ng Tuna", ["grilled tuna jaw"], ["tuna", "panga"]),
        ("laing-tinapa", "Ginataang Tinapa", ["smoked fish in coconut milk"], ["ginataang", "tinapa"]),
    ],
    "sabaw": [
        ("sinigang-baboy", "Sinigang na Baboy", ["pork sinigang", "sour pork soup"], ["pork", "sinigang-na-baboy"]),
        ("sinigang-baka", "Sinigang na Baka", ["beef sinigang"], ["beef", "sinigang"]),
        ("bulalo", "Bulalo", ["beef shank soup"], ["beef", "bulalo"]),
        ("nilagang-baka", "Nilagang Baka", ["boiled beef soup"], ["nilagang", "baka"]),
        ("nilagang-baboy", "Nilagang Baboy", ["boiled pork soup"], ["nilagang", "baboy"]),
        ("tinolang-manok", "Tinolang Manok", ["chicken tinola"], ["tinolang", "manok"]),
        ("sopas", "Sopas", ["filipino chicken macaroni soup"], ["sopas"]),
        ("batchoy", "La Paz Batchoy", ["batchoy"], ["batchoy"]),
        ("molo", "Pancit Molo", ["molo soup"], ["molo"]),
        ("goto", "Goto", ["rice porridge with tripe"], ["goto"]),
        ("arroz-caldo", "Arroz Caldo", ["chicken rice porridge"], ["arroz", "caldo"]),
        ("papaitan", "Papaitan", ["goat innards soup"], ["papaitan"]),
        ("ginataang-munggo", "Ginataang Munggo", [], ["ginataang", "munggo"]),
        ("lugaw", "Lugaw", ["rice porridge"], ["lugaw"]),
        ("tinolang-tahong", "Tinolang Tahong", ["mussel soup"], ["tinolang", "tahong"]),
        ("cabbage-soup", "Sinabawang Gulay", ["vegetable soup"], ["sinabawang", "gulay"]),
        ("misua-patola", "Misua with Patola", ["misua soup"], ["misua", "patola"]),
        ("chicken-sotanghon-soup", "Chicken Sotanghon Soup", [], ["chicken", "sotanghon", "soup"]),
        ("pochero-soup", "Pocherong Baka", ["beef pochero"], ["beef", "pochero"]),
        ("balbacua", "Balbacua", ["beef stew"], ["balbacua"]),
        ("cansi", "Cansi", ["ilonggo beef soup"], ["cansi"]),
        ("sinampalukang-manok", "Sinampalukang Manok", [], ["sinampalukang"]),
        ("pesang-baboy", "Pesang Baboy at Manok", [], ["pesang", "baboy"]),
    ],
    "gulay": [
        ("pinakbet", "Pinakbet", ["pakbet"], ["pinakbet-tagalog"]),
        ("ginataang-langka", "Ginataang Langka", ["jackfruit in coconut milk"], ["ginataang", "langka"]),
        ("laing", "Laing", ["taro leaves in coconut milk"], ["laing", "gabi"]),
        ("chopsuey", "Chopsuey", ["chop suey"], ["chopsuey"]),
        ("ginataang-gulay", "Ginataang Gulay", ["vegetables in coconut milk"], ["ginataang", "gulay"]),
        ("ginisang-monggo", "Ginisang Monggo", ["mung bean stew"], ["ginisang", "monggo"]),
        ("adobong-kangkong", "Adobong Kangkong", ["water spinach adobo"], ["adobong", "kangkong"]),
        ("ampalaya-con-carne", "Ampalaya con Carne", ["bitter gourd with beef"], ["ampalaya", "carne"]),
        ("ginisang-ampalaya", "Ginisang Ampalaya", ["sauteed bitter gourd"], ["ginisang", "ampalaya"]),
        ("tortang-talong", "Tortang Talong", ["eggplant omelette"], ["tortang", "talong"]),
        ("ginataang-kalabasa", "Ginataang Kalabasa", ["squash in coconut milk"], ["ginataang", "kalabasa"]),
        ("ginisang-sayote", "Ginisang Sayote", ["sauteed chayote"], ["ginisang", "sayote"]),
        ("ginisang-repolyo", "Ginisang Repolyo", ["sauteed cabbage"], ["ginisang", "repolyo"]),
        ("ginisang-upo", "Ginisang Upo", ["sauteed bottle gourd"], ["ginisang", "upo"]),
        ("ginataang-sitaw", "Ginataang Sitaw at Kalabasa", [], ["ginataang", "sitaw"]),
        ("adobong-sitaw", "Adobong Sitaw", ["string bean adobo"], ["adobong", "sitaw"]),
        ("ginisang-togue", "Ginisang Togue", ["sauteed bean sprouts"], ["ginisang", "togue"]),
        ("dinengdeng", "Dinengdeng", [], ["dinengdeng"]),
        ("utan-bisaya", "Utan Bisaya", ["visayan vegetable soup"], ["utan", "bisaya"]),
        ("ensaladang-talong", "Ensaladang Talong", ["eggplant salad"], ["ensaladang", "talong"]),
        ("atchara", "Atchara", ["pickled papaya"], ["atchara"]),
        ("lumpiang-gulay", "Lumpiang Gulay", ["vegetable spring roll"], ["lumpiang", "gulay"]),
        ("dinakdakan", "Dinakdakan", [], ["dinakdakan"]),
        ("ginisang-labanos", "Ginisang Labanos", ["sauteed radish"], ["ginisang", "labanos"]),
    ],
    "pancit at kanin": [
        ("pancit-canton", "Pancit Canton", [], ["pancit", "canton"]),
        ("pancit-bihon", "Pancit Bihon", ["bihon guisado"], ["pancit", "bihon"]),
        ("palabok", "Pancit Palabok", ["palabok"], ["pancit", "palabok"]),
        ("pancit-malabon", "Pancit Malabon", [], ["pancit", "malabon"]),
        ("pancit-habhab", "Pancit Habhab", ["lucban pancit"], ["pancit", "habhab"]),
        ("pancit-sotanghon", "Pancit Sotanghon", [], ["pancit", "sotanghon"]),
        ("lomi", "Lomi", ["batangas lomi"], ["lomi"]),
        ("mami", "Chicken Mami", [], ["chicken", "mami"]),
        ("bringhe", "Bringhe", ["filipino paella"], ["bringhe"]),
        ("paella", "Paella Filipina", [], ["paella"]),
        ("sinangag", "Sinangag", ["garlic fried rice"], ["garlic", "fried", "rice"]),
        ("java-rice", "Java Rice", [], ["java", "rice"]),
        ("arroz-valenciana", "Arroz a la Valenciana", [], ["valenciana"]),
        ("pancit-luglug", "Pancit Luglug", [], ["pancit", "luglug"]),
        ("bam-i", "Pancit Bam-i", [], ["bam-i"]),
        ("spaghetti", "Filipino Spaghetti", [], ["filipino", "spaghetti"]),
        ("baked-macaroni", "Baked Macaroni", [], ["baked", "macaroni"]),
        ("pancit-lomi-batangas", "Pancit Lomi Batangas", [], ["batangas", "lomi"]),
        ("bibingkang-kanin", "Bibingkang Malagkit", [], ["bibingkang", "malagkit"]),
        ("champorado", "Champorado", ["chocolate rice porridge"], ["champorado"]),
        ("miki-bihon", "Miki Bihon", [], ["miki", "bihon"]),
        ("pancit-cabagan", "Pancit Cabagan", [], ["pancit", "cabagan"]),
    ],
    "pulutan at meryenda": [
        ("lumpiang-shanghai", "Lumpiang Shanghai", ["spring rolls"], ["lumpiang", "shanghai"]),
        ("lumpiang-sariwa", "Lumpiang Sariwa", ["fresh spring roll"], ["lumpiang", "sariwa"]),
        ("tokwat-baboy", "Tokwa't Baboy", [], ["tokwa", "baboy"]),
        ("kwek-kwek", "Kwek-Kwek", ["quail egg fritters"], ["kwek"]),
        ("okoy", "Okoy", ["ukoy", "shrimp fritters"], ["okoy"]),
        ("chicharon", "Chicharon", ["pork cracklings"], ["chicharon", "bulaklak"]),
        ("isaw", "Isaw", ["grilled chicken intestines"], ["isaw"]),
        ("turon", "Turon", ["banana spring roll"], ["turon"]),
        ("banana-cue", "Banana Cue", ["bananacue"], ["banana", "cue"]),
        ("camote-cue", "Camote Cue", ["kamote que", "kamote cue"], ["kamote", "que"]),
        ("dynamite", "Dynamite Lumpia", ["cheese sticks chili"], ["dynamite"]),
        ("cheese-sticks", "Cheese Sticks", [], ["cheese", "sticks"]),
        ("empanada", "Empanada", ["ilocos empanada"], ["empanada"]),
        ("siomai", "Siomai", ["pork siomai"], ["siomai"]),
        ("siopao", "Siopao", ["asado siopao"], ["siopao"]),
        ("fishball", "Fish Ball", ["fishballs"], ["fish", "ball"]),
        ("food-for-the-gods", "Food for the Gods", ["date bar"], ["food-for-the-gods"]),
        ("pianono", "Pianono", [], ["pianono"]),
        ("tokneneng", "Tokneneng", [], ["tokneneng"]),
        ("maruya", "Maruya", ["banana fritters"], ["maruya"]),
        ("ginataang-bilo-bilo", "Ginataang Bilo-Bilo", [], ["ginataang", "bilo-bilo"]),
        ("lumpiang-ubod", "Lumpiang Ubod", ["heart of palm spring roll"], ["lumpiang", "ubod"]),
        ("pinaputok-na-tilapia", "Pinaputok na Tilapia", [], ["pinaputok"]),
        ("lechon-manok", "Lechon Manok", ["roast chicken"], ["lechon", "manok"]),
        ("inihaw-na-liempo", "Inihaw na Liempo", ["grilled pork belly"], ["inihaw", "liempo"]),
        ("pork-barbecue", "Pork Barbecue", ["filipino bbq skewers"], ["pork", "barbecue"]),
    ],
    "panghimagas": [
        ("leche-flan", "Leche Flan", ["creme caramel"], ["leche", "flan"]),
        ("halo-halo", "Halo-Halo", [], ["halo-halo"]),
        ("bibingka", "Bibingka", ["rice cake"], ["bibingka"]),
        ("puto-bumbong", "Puto Bumbong", [], ["puto", "bumbong"]),
        ("puto", "Puto", ["steamed rice cake"], ["puto", "cheese"]),
        ("kutsinta", "Kutsinta", ["cuchinta"], ["kutsinta"]),
        ("sapin-sapin", "Sapin-Sapin", [], ["sapin-sapin"]),
        ("biko", "Biko", ["sweet sticky rice"], ["biko"]),
        ("maja-blanca", "Maja Blanca", ["coconut pudding"], ["maja", "blanca"]),
        ("buko-pandan", "Buko Pandan", [], ["buko", "pandan"]),
        ("ube-halaya", "Ube Halaya", ["purple yam jam"], ["ube", "halaya"]),
        ("brazo-de-mercedes", "Brazo de Mercedes", [], ["brazo"]),
        ("sans-rival", "Sans Rival", [], ["sans", "rival"]),
        ("ensaymada", "Ensaymada", [], ["ensaymada"]),
        ("yema", "Yema", ["custard candy"], ["yema"]),
        ("pastillas", "Pastillas de Leche", [], ["pastillas"]),
        ("polvoron", "Polvoron", [], ["polvoron"]),
        ("cassava-cake", "Cassava Cake", [], ["cassava", "cake"]),
        ("pichi-pichi", "Pichi-Pichi", [], ["pichi"]),
        ("palitaw", "Palitaw", [], ["palitaw"]),
        ("suman", "Suman", ["sticky rice roll"], ["suman"]),
        ("ginataang-mais", "Ginataang Mais", ["corn pudding"], ["ginataang", "mais"]),
        ("mango-float", "Mango Float", ["crema de mangga"], ["mango", "float"]),
        ("buko-salad", "Buko Salad", [], ["buko", "salad"]),
        ("fruit-salad", "Filipino Fruit Salad", [], ["fruit", "salad"]),
        ("taho", "Taho", [], ["taho"]),
        ("tibok-tibok", "Tibok-Tibok", [], ["tibok"]),
        ("silvanas", "Silvanas", [], ["silvanas"]),
        ("mamon", "Mamon", ["sponge cake"], ["mamon"]),
        ("pan-de-sal", "Pandesal", ["pan de sal"], ["pandesal"]),
        ("nilupak", "Nilupak", ["mashed cassava"], ["nilupak"]),
        ("espasol", "Espasol", [], ["espasol"]),
        ("egg-pie", "Egg Pie", [], ["egg", "pie"]),
        ("buko-pie", "Buko Pie", [], ["buko", "pie"]),
        ("binatog", "Binatog", ["boiled corn kernels"], ["binatog"]),
        ("crema-de-fruta", "Crema de Fruta", [], ["crema", "fruta"]),
    ],
}


# Dishes whose best page the slug scorer cannot reach: the top-scoring slug exists
# but carries no usable recipe schema, or names a different dish entirely.
OVERRIDES = {
    "bistek": "https://www.kawalingpinoy.com/bistek/",
    "halo-halo": "https://www.kawalingpinoy.com/halo-halo/",
    "pork-barbecue": "https://panlasangpinoy.com/inihaw-na-baboy/",
}
assert list(CATEGORIES) == list(DISHES), "every category needs an English name"
